name: Build backend

on:
  pull_request:
    paths:
      - "backend/**"
      
  push:
    branches: 
      - main
    paths: 
      - "backend/**"

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4.0.0
      with:
        distribution: oracle
        java-version-file: backend/.java-version
        cache: "gradle"
        cache-dependency-path: |
          backend/*.gradle*
          backend/**/gradle-wrapper.properties

    - name: Build
      run: cd backend && gradle build
