name: Skip backend on ignored paths

on:
  pull_request:
    paths-ignore:
      - "backend/**"

  push:
    branches: 
      - main
    paths-ignore:
      - "backend/**"

jobs:
  build-backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required"'
