name: Skip frontend on ignored paths

on:
  pull_request:
    paths-ignore:
      - "frontend/**"

  push:
    branches: 
      - main
    paths-ignore:
      - "frontend/**"

jobs:
  build-frontend:
    name: Approve
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "No build required"'
